# Generated by Django 5.2.3 on 2025-06-21 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
